version: '3.8'

services:
  # client:
  #   build: ./frontmern
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - server

   vite-frontend:
     build: ./front-on-vite/my-app
     ports:
       - "3000:80" # Локальный порт 3000 → nginx внутри контейнера (порт 80)
     container_name: vite-frontend
     restart: unless-stopped


  server:
    build: ./backendmern
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
