# 1. Базовый образ с Node.js
FROM node:20-alpine AS builder

# 2. Рабочая директория внутри контейнера
WORKDIR /app

# 3. Копируем зависимости
COPY package*.json ./
RUN npm install

# 4. Копируем весь проект
COPY . .

# 5. Сборка Vite-приложения
RUN npm run build

# ------------------------------

# 6. Сервер на nginx для продакшена
FROM nginx:stable-alpine

# 7. Копируем собранные файлы в папку Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# 8. Копируем дефолтную конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 9. Открываем порт 80
EXPOSE 80

# 10. Запуск nginx
CMD ["nginx", "-g", "daemon off;"]
